create table if not exists public.api_usage_daily (
    actor_key text not null,
    usage_date date not null default current_date,
    spent_microusd bigint not null default 0 check (spent_microusd >= 0),
    llm_call_count integer not null default 0 check (llm_call_count >= 0),
    updated_at timestamptz not null default timezone('utc', now()),
    primary key (actor_key, usage_date)
);

alter table public.api_usage_daily enable row level security;

create table if not exists public.api_request_events (
    id bigint generated by default as identity primary key,
    actor_key text not null,
    endpoint text not null,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.api_request_events enable row level security;

create index if not exists api_request_events_actor_created_idx
    on public.api_request_events (actor_key, created_at desc);

create or replace function public.claim_api_request_slot(
    p_actor_key text,
    p_endpoint text,
    p_daily_limit_microusd bigint,
    p_burst_limit integer,
    p_window_seconds integer
)
returns table (
    spent_microusd bigint,
    llm_call_count integer,
    recent_request_count integer,
    remaining_microusd bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_spent bigint := 0;
    v_llm_calls integer := 0;
    v_recent integer := 0;
begin
    select
        coalesce((
            select d.spent_microusd
            from public.api_usage_daily as d
            where d.actor_key = p_actor_key
              and d.usage_date = current_date
        ), 0),
        coalesce((
            select d.llm_call_count
            from public.api_usage_daily as d
            where d.actor_key = p_actor_key
              and d.usage_date = current_date
        ), 0)
    into
        v_spent,
        v_llm_calls;

    if v_spent >= p_daily_limit_microusd then
        raise exception 'DAILY_LIMIT_EXCEEDED';
    end if;

    select count(*)::integer
    into v_recent
    from public.api_request_events as e
    where e.actor_key = p_actor_key
      and e.created_at >= timezone('utc', now()) - (interval '1 second' * greatest(p_window_seconds, 1));

    if v_recent >= p_burst_limit then
        raise exception 'BURST_LIMIT_EXCEEDED';
    end if;

    insert into public.api_request_events (actor_key, endpoint)
    values (p_actor_key, p_endpoint);

    return query
    select
        v_spent,
        v_llm_calls,
        v_recent + 1,
        greatest(p_daily_limit_microusd - v_spent, 0);
end;
$$;

create or replace function public.record_api_usage(
    p_actor_key text,
    p_cost_microusd bigint
)
returns table (
    spent_microusd bigint,
    llm_call_count integer
)
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.api_usage_daily (
        actor_key,
        usage_date,
        spent_microusd,
        llm_call_count,
        updated_at
    )
    values (
        p_actor_key,
        current_date,
        greatest(p_cost_microusd, 0),
        1,
        timezone('utc', now())
    )
    on conflict (actor_key, usage_date)
    do update
    set
        spent_microusd = public.api_usage_daily.spent_microusd + greatest(excluded.spent_microusd, 0),
        llm_call_count = public.api_usage_daily.llm_call_count + 1,
        updated_at = timezone('utc', now());

    return query
    select
        d.spent_microusd,
        d.llm_call_count
    from public.api_usage_daily as d
    where d.actor_key = p_actor_key
      and d.usage_date = current_date;
end;
$$;

create or replace function public.get_api_usage_summary(
    p_actor_key text,
    p_daily_limit_microusd bigint
)
returns table (
    used_microusd bigint,
    remaining_microusd bigint,
    request_count integer
)
language sql
security definer
set search_path = ''
as $$
    select
        coalesce(d.spent_microusd, 0) as used_microusd,
        greatest(p_daily_limit_microusd - coalesce(d.spent_microusd, 0), 0) as remaining_microusd,
        coalesce(d.llm_call_count, 0) as request_count
    from (
        select 1 as singleton
    ) as s
    left join public.api_usage_daily as d
      on d.actor_key = p_actor_key
     and d.usage_date = current_date;
$$;

revoke execute on function public.claim_api_request_slot(text, text, bigint, integer, integer) from public;
revoke execute on function public.claim_api_request_slot(text, text, bigint, integer, integer) from anon, authenticated;
revoke execute on function public.record_api_usage(text, bigint) from public;
revoke execute on function public.record_api_usage(text, bigint) from anon, authenticated;
revoke execute on function public.get_api_usage_summary(text, bigint) from public;
revoke execute on function public.get_api_usage_summary(text, bigint) from anon, authenticated;
